[build]
functions = "functions"

[[redirects]]
from = "api/*"
status = 200
to = "/.netlify/functions/:splat"

[[redirects]]
from = "/*"
status = 200
to = "/index.html"

[[headers]]
for = "/*"
[headers.values]
Access-Control-Allow-Origin = "*"
